### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by ScorpioT1000** [LXSMNSYC/Lua-Wc3-Module#1]
Hi, this is a good idea but i cannot even copy or install this

https://imgur.com/bbP0NSD

**Comment by lxsmnsyc** [comment]
you only need to copy the source code of one of the two init files here in this repo, and paste it in a script in your Wc3 map. Since Wc3 maps compiles Lua into a single file, using the `require "Lua-Wc3-Module"` is already unnecessary.

**Comment by lxsmnsyc** [comment]
![Screenshot from 2019-05-14 07-48-37](https://user-images.githubusercontent.com/4783372/57661286-c05d1b80-761c-11e9-8460-1454884c05ab.png)

Strogg sent me this, hope this helps

**Comment by ScorpioT1000** [comment]
Ok thanks we already clarified the issue on XGM. I hope this will be the unified solution for all lua wc3 developers. What do you think about to create a repository and simple module management system (like npm)?
